ALTER TYPE "OrderStatus"
ADD VALUE IF NOT EXISTS 'PAYMENT_VERIFIED';

ALTER TYPE "OrderStatus"
ADD VALUE IF NOT EXISTS 'PAYMENT_REJECTED';

ALTER TYPE "OrderStatus"
ADD VALUE IF NOT EXISTS 'READY_FOR_DELIVERY';

ALTER TYPE "OrderStatus"
ADD VALUE IF NOT EXISTS 'OUT_FOR_DELIVERY';

ALTER TYPE "OrderStatus"
ADD VALUE IF NOT EXISTS 'REJECTED';
